---
apiVersion: v1
kind: Config
clusters:
  - name: kubernetes
    cluster:
      certificate-authority: /etc/kubelet/pki_ca.crt
      server: https://CA344BF76438EC7BAFF8096F47F73097.yl4.eks-cluster.us-east-2.api.aws
current-context: kubelet
contexts:
  - name: kubelet
    context:
      cluster: kubernetes
      user: kubelet
users:
  - name: kubelet
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws
        args:
          - "eks"
          - "get-token"
          - "--cluster-name"
          - "lightning-unstable"
          - "--region"
          - "us-east-2"
