# All the subnetwork and their ranges are consolidated here.
# They may be created or used in other layers, but we need them all in one place to prevent overlap and keep things clear.
# Worth noting, us-east-1 has the most availability zones at 6. However one of them is EVIL and should not be used.
# So I'm prone to segmenting things in groups of 5.
[ipv4]
dualstack-public-a = "0.0/20"
dualstack-public-b = "16.0/20"
dualstack-public-c = "32.0/20"

dualstack-private-a = "80.0/20"
dualstack-private-b = "96.0/20"
dualstack-private-c = "112.0/20"

# ipv6 subnets are always /64 by convention.
# Rather than strings, we give a number, and we add that number to the vpc cidr.
# Number is 0x0 to 0xff.
[ipv6]
dualstack-public-a = 0x01
dualstack-public-b = 0x02
dualstack-public-c = 0x03

dualstack-private-a = 0x06
dualstack-private-b = 0x07
dualstack-private-c = 0x08

ipv6only-public-a = 0x16
ipv6only-public-b = 0x17
ipv6only-public-c = 0x18

ipv6only-private-a = 0x1b
ipv6only-private-b = 0x1c
ipv6only-private-c = 0x1d

# ipv6 only subnets that pod ip range ENIs are assigned from
pods-only-a = 0x21
pods-only-b = 0x22
pods-only-c = 0x23
