---
kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1
providers:
- name: docker-credential-ecr-login
  env:
    - name: AWS_USE_DUALSTACK_ENDPOINT
      value: "true"
  matchImages:
  - "*.dkr.ecr.*.amazonaws.com"
  - "*.dkr-ecr.*.on.aws"
  - "*.dkr.ecr.*.amazonaws.com.cn"
  - "*.dkr-ecr.*.on.amazonwebservices.com.cn"
  - "*.dkr.ecr-fips.*.amazonaws.com"
  - "*.dkr-ecr-fips.*.on.aws"
  - "*.dkr.ecr.*.c2s.ic.gov"
  - "*.dkr.ecr.*.sc2s.sgov.gov"
  - "*.dkr.ecr.*.cloud.adc-e.uk"
  - "*.dkr.ecr.*.csp.hci.ic.gov"
  - "*.dkr.ecr.*.amazonaws.eu"
  - "public.ecr.aws"
  - "ecr-public.aws.com" # dualstack public
  - "*.dkr-ecr.*.on.aws" # dualstack private

  defaultCacheDuration: 12h0m0s
  apiVersion: credentialprovider.kubelet.k8s.io/v1
